### ISSUE TITLE
Publish all the helm charts through github pages

### ISSUE THREAD

**Issue by bravecobra** [oracle/helm-charts#10]
Publishing the helm charts to github pages helps avoid having to checkout the repo and build it yourself.
You can easily add a workflow using the following Github Action: https://github.com/stefanprodan/helm-gh-pages

I would suggest publishing ALL charts of this repository, including the oracledb one.

**Comment by streamnsight** [comment]
@bravecobra 
It is published through github pages, at https://oracle.github.io/helm-charts
It is just published in the master branch, and not on a separate branch.

You can checkout the chart repo with 
```
helm repo add oracle https://oracle.github.io/helm-charts
```

**Comment by bravecobra** [comment]
Could you add `oracledb` as that was the one I was looking for?

**Comment by streamnsight** [comment]
@bravecobra I don't own the oracledb chart, so it would have to be up to the owner of the chart on the docker-image repo to move it here. I'm not sure who that is.
There is a subchart for oracle db in the soa-suite chart, but it is for demo / dev only, not for production.

I would suggest you open an issue on the docker-image repo to ask them to move to the official chart repo.
Thanks

**Comment by bravecobra** [comment]
I worked around it by using the [oracle-database-operator](https://github.com/oracle/oracle-database-operator) instead of installing it through a helm file.
